export default {
  LIMITED_NUMBER_COMMENTS: 5,
  COMMENT_MAX_LENGTH: 140,

  SCALE_MAX: 100,
  SCALE_MIN: 25,
  SCALE_STEP: 25,

  CHROMESEPIA_MIN_VALUE: 0,
  CHROMESEPIA_MAX_VALUE: 1,
  CHROMESEPIA_STEP: 0.1,
};

