export default {
  LIMITED_NUMBER_COMMENTS: 5,
  COMMENT_MAX_LENGTH: 140,
  HASHTAG_MAX_LENGTH: 20,

  SCALE_MAX: 100,
  SCALE_MIN: 25,
  SCALE_STEP: 25,

  CHROMESEPIA_MIN_VALUE: 0,
  CHROMESEPIA_MAX_VALUE: 1,
  CHROMESEPIA_STEP: 0.1,
  MARVIN_MIN_VALUE: 0,
  MARVIN_MAX_VALUE: 100,
  MARVIN_STEP: 1,
  PHOBOS_MIN_VALUE: 0,
  PHOBOS_MAX_VALUE: 3,
  PHOBOS_STEP: 0.1,
  HEAT_MIN_VALUE: 1,
  HEAT_MAX_VALUE: 3,
  HEAT_STEP: 0.1,
  NONE_MIN_VALUE: 0,
  NONE_MAX_VALUE: 100,
  NONE_STEP: 1,
  NONE_START: 100,

  API_DATA_URL: 'https://26.javascript.pages.academy/kekstagram',

  DRAW_DELAY: 500,
  RANDOM_PHOTO_COUNT: 10,
};

